# Generated by Django 5.0.1 on 2024-01-11 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appareil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('type', models.CharField(blank=True, max_length=50)),
                ('cote', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name': 'Appareil',
                'verbose_name_plural': 'Appareils',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Devis',
                'verbose_name_plural': 'Deviss',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Panneau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('PV', models.IntegerField()),
                ('R_load', models.IntegerField()),
                ('M_load', models.IntegerField()),
                ('cote', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='TypePanneau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'TypePanneau',
                'verbose_name_plural': 'TypePanneaus',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Devis_Appareil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('appareil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coca.appareil')),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coca.devis')),
            ],
            options={
                'verbose_name': 'Devis_Appareil',
                'verbose_name_plural': 'Devis_Appareils',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Type_Panneau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.IntegerField()),
                ('panneau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coca.panneau')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coca.typepanneau')),
            ],
            options={
                'verbose_name': 'Type_Panneau',
                'verbose_name_plural': 'Type_Panneaus',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
