# Generated by Django 5.0.1 on 2024-01-14 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type_panneau',
            name='panneau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='coca.panneau'),
        ),
    ]
