# Generated by Django 5.0.1 on 2024-02-01 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coca', '0002_alter_type_panneau_panneau'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformationsInternaute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('addres', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='devis',
            name='nom',
        ),
        migrations.AddField(
            model_name='devis',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='devis',
            name='internaute_temp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coca.informationsinternaute'),
        ),
    ]
