# Generated by Django 5.0.1 on 2024-02-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coca', '0003_informationsinternaute_remove_devis_nom_devis_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type_panneau',
            name='panneau',
        ),
        migrations.RemoveField(
            model_name='type_panneau',
            name='type',
        ),
        migrations.RenameField(
            model_name='devis',
            old_name='total',
            new_name='energie_T',
        ),
        migrations.AddField(
            model_name='appareil',
            name='puissance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='devis_appareil',
            name='energie_T',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='devis_appareil',
            name='numHours',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.DeleteModel(
            name='Panneau',
        ),
        migrations.DeleteModel(
            name='Type_Panneau',
        ),
        migrations.DeleteModel(
            name='TypePanneau',
        ),
    ]
