# Generated by Django 5.0.1 on 2024-02-25 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coca', '0006_informationsinternaute_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationsinternaute',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
